# Exploratory Data Analysis

### Loading Data and Sample Preview

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)  # Display all columns in the output

# Load the datasets
declarations = pd.read_csv('../fema_data/declarations.csv')
dis_summ = pd.read_csv('../fema_data/disaster_summaries.csv')
pub_assistance = pd.read_csv('../fema_data/public_assistance.csv')

# Display the first few rows of each dataset
def print_dataset_info():
    df_dict = {
        'Declarations': declarations,
        'Disaster Summaries': dis_summ,
        'Public Assistance': pub_assistance
    }
    
    for name, df in df_dict.items():
        print(f"Dataset: {name}")
        print(f"{df.shape[0]} rows and {df.shape[1]} columns")
        print(df.head().to_string())
        print("\n")

print_dataset_info()

Dataset: Declarations
32473 rows and 7 columns
   disasterNumber state  incidentType           declarationDate         incidentBeginDate           incidentEndDate declarationType
0            5529    OR          Fire  2024-08-09T00:00:00.000Z  2024-08-08T00:00:00.000Z                       NaN              FM
1            5528    OR          Fire  2024-08-06T00:00:00.000Z  2024-08-04T00:00:00.000Z                       NaN              FM
2            5527    OR          Fire  2024-08-02T00:00:00.000Z  2024-08-02T00:00:00.000Z                       NaN              FM
3            4312    CA  Severe Storm  2017-05-02T00:00:00.000Z  2017-02-08T00:00:00.000Z  2017-02-11T00:00:00.000Z              DR
4            4251    AL  Severe Storm  2016-01-21T00:00:00.000Z  2015-12-23T00:00:00.000Z  2015-12-31T00:00:00.000Z              DR


Dataset: Disaster Summaries
2132 rows and 6 columns
   disasterNumber  totalAmountIhpApproved  totalAmountHaApproved  totalAmountOnaApproved  totalObligatedAmountPa  totalObligatedAmountHmgp
0            3601                     NaN                    NaN                     NaN                     NaN                       NaN
1            3602                     NaN                    NaN                     NaN                     NaN                       NaN
2            4420             27279186.25            24356998.74              2922187.51            5.297529e+08               38905824.97
3            1971             77097372.06            57302364.20             19795007.86            2.010424e+08               63346282.14
4            4015                     NaN                    NaN                     NaN            5.553128e+06                1762074.09


Dataset: Public Assistance
400014 rows and 6 columns
   pwNumber  disasterNumber  stateNumberCode incidentType  totalObligated projectSize
0         6            3384               72    Hurricane        44834.99       Small
1        17            3384               72    Hurricane        15249.85       Small
2        27            3384               72    Hurricane        36996.46       Large
3        33            3384               72    Hurricane         7390.12       Small
4        35            3384               72    Hurricane       136697.32       Large

Note that each records in each dataset is only from 2010 onwards

In [3]:
dis_summ.head()

,disasterNumber,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountHmgp
0,3601,NaN,NaN,NaN,NaN,NaN
1,3602,NaN,NaN,NaN,NaN,NaN
2,4420,27279186.25,24356998.74,2922187.51,5.297529e+08,38905824.97
3,1971,77097372.06,57302364.20,19795007.86,2.010424e+08,63346282.14
4,4015,NaN,NaN,NaN,5.553128e+06,1762074.09

In [4]:
declarations.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType
0,5529,OR,Fire,2024-08-09T00:00:00.000Z,2024-08-08T00:00:00.000Z,NaN,FM
1,5528,OR,Fire,2024-08-06T00:00:00.000Z,2024-08-04T00:00:00.000Z,NaN,FM
2,5527,OR,Fire,2024-08-02T00:00:00.000Z,2024-08-02T00:00:00.000Z,NaN,FM
3,4312,CA,Severe Storm,2017-05-02T00:00:00.000Z,2017-02-08T00:00:00.000Z,2017-02-11T00:00:00.000Z,DR
4,4251,AL,Severe Storm,2016-01-21T00:00:00.000Z,2015-12-23T00:00:00.000Z,2015-12-31T00:00:00.000Z,DR

In [5]:
pub_assistance.head()

,pwNumber,disasterNumber,stateNumberCode,incidentType,totalObligated,projectSize
0,6,3384,72,Hurricane,44834.99,Small
1,17,3384,72,Hurricane,15249.85,Small
2,27,3384,72,Hurricane,36996.46,Large
3,33,3384,72,Hurricane,7390.12,Small
4,35,3384,72,Hurricane,136697.32,Large

In [6]:
pub_assistance.groupby('disasterNumber').agg({'totalObligated': 'sum'}).reset_index().sort_values(by='totalObligated', ascending=False)

      disasterNumber  totalObligated
538             4339    3.633175e+10
539             4340    2.206285e+10
674             4480    1.755757e+10
676             4482    1.533094e+10
288             4085    1.484767e+10
...              ...             ...
187             3562    1.057804e+04
202             3614    1.023638e+04
1062            4894    7.500000e+03
160             3490    7.152970e+03
141             3341    3.194360e+03

[1067 rows x 2 columns]

In [7]:
pub_assistance[['incidentType', 'projectSize']][pub_assistance['disasterNumber'] == 4339]

       incidentType projectSize
622       Hurricane       Large
815       Hurricane       Large
835       Hurricane       Small
849       Hurricane       Small
861       Hurricane       Large
...             ...         ...
399714    Hurricane       Large
399715    Hurricane       Large
399716    Hurricane       Small
399717    Hurricane       Large
399723    Hurricane       Small

[11039 rows x 2 columns]

In [8]:
pub_assistance.isnull().sum()

pwNumber           0
disasterNumber     0
stateNumberCode    0
incidentType       0
totalObligated     0
projectSize        0
dtype: int64

In [9]:
dis_summ.isnull().sum()

disasterNumber                 0
totalAmountIhpApproved      1757
totalAmountHaApproved       1813
totalAmountOnaApproved      1758
totalObligatedAmountPa       522
totalObligatedAmountHmgp     329
dtype: int64

In [10]:
declarations.isnull().sum()

disasterNumber         0
state                  0
incidentType           0
declarationDate        0
incidentBeginDate      0
incidentEndDate      220
declarationType        0
dtype: int64

In [11]:
dis_summ[dis_summ['totalAmountIhpApproved'].notnull()][['totalAmountIhpApproved', 'totalAmountOnaApproved', 'totalAmountHaApproved']]

      totalAmountIhpApproved  totalAmountOnaApproved  totalAmountHaApproved
2                27279186.25              2922187.51            24356998.74
3                77097372.06             19795007.86            57302364.20
12               10602928.54               897055.04             9705873.50
51               10616929.18             10616929.18                    NaN
54                1754570.75               333564.29             1421006.46
...                      ...                     ...                    ...
1760              1326459.25               576293.03              750166.22
1761              7975406.20              2439578.63             5535827.57
1762              3540571.83               989310.25             2551261.58
1763               935304.83               270081.05              665223.78
1764              5391278.01              1071978.47             4319299.54

[375 rows x 3 columns]

As reported [here](https://www.fema.gov/sites/default/files/2020-05/IHP_Unified_Guidance_FINAL_09272016_0.pdf), `totalAmountIhpApproved` = `totalAmountOnaApproved` + `totalAmountHaApproved`.

So majorly, total budget allocation from the government towards disaster recovery is `totalAmountIhpApproved` + `totalObligatedAmountPa`. Total budget allocation from the government towards hazard/disaster prevention and mitigation is `totalObligatedAmountHmgp`

### Data Cleaning

In [12]:
# Convert date columns to datetime format
date_cols = ["declarationDate", "incidentBeginDate", "incidentEndDate"]

for col in date_cols:
    declarations[col] = pd.to_datetime(declarations[col], errors='coerce')

In [13]:
# Ensure numeric columns are number types
num_cols_summ = [
    "totalAmountIhpApproved",
    "totalAmountHaApproved",
    "totalAmountOnaApproved",
    "totalObligatedAmountPa",
    "totalObligatedAmountHmgp"
]

for col in num_cols_summ:
    dis_summ[col] = pd.to_numeric(dis_summ[col], errors='coerce')

pub_assistance["totalObligated"] = pd.to_numeric(pub_assistance["totalObligated"], errors='coerce')

In [14]:
(pub_assistance["totalObligated"] == 0).sum()

np.int64(0)

As earlier determined, no null values in pub_assistance and no project had totalObligated from government as zero. totalObligated > 0 always. This means there are no invalid projects.

### Feature Engineering

In [15]:
# engineer time-based features from declarations dataset
decl = declarations.copy()

decl["declaration_year"] = decl["declarationDate"].dt.year
decl["declaration_month"] = decl["declarationDate"].dt.month
decl["declaration_quarter"] = decl["declarationDate"].dt.quarter

decl["incident_duration_days"] = (
    decl["incidentEndDate"] - decl["incidentBeginDate"]
).dt.days

decl["declaration_lag_days"] = (
    decl["declarationDate"] - decl["incidentBeginDate"]
).dt.days

decl["incident_open_flag"] = decl["incidentEndDate"].isna().astype(int)

decl.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType,declaration_year,declaration_month,declaration_quarter,incident_duration_days,declaration_lag_days,incident_open_flag
0,5529,OR,Fire,2024-08-09 00:00:00+00:00,2024-08-08 00:00:00+00:00,NaT,FM,2024,8,3,NaN,1,1
1,5528,OR,Fire,2024-08-06 00:00:00+00:00,2024-08-04 00:00:00+00:00,NaT,FM,2024,8,3,NaN,2,1
2,5527,OR,Fire,2024-08-02 00:00:00+00:00,2024-08-02 00:00:00+00:00,NaT,FM,2024,8,3,NaN,0,1
3,4312,CA,Severe Storm,2017-05-02 00:00:00+00:00,2017-02-08 00:00:00+00:00,2017-02-11 00:00:00+00:00,DR,2017,5,2,3.0,83,0
4,4251,AL,Severe Storm,2016-01-21 00:00:00+00:00,2015-12-23 00:00:00+00:00,2015-12-31 00:00:00+00:00,DR,2016,1,1,8.0,29,0

In [16]:
# engineer target variable in disaster summaries dataset
summ = dis_summ.copy()

summ["target_pa_cost"] = summ["totalObligatedAmountPa"].fillna(0)

summ["target_total_recovery_cost"] = (
    summ["totalAmountIhpApproved"].fillna(0)
    + summ["totalObligatedAmountPa"].fillna(0)
    + summ["totalObligatedAmountHmgp"].fillna(0)
)

# Log transform (to avoid skewness and handle zero values)
summ["log_target_pa_cost"] = np.log1p(summ["target_pa_cost"])
summ["log_target_total_cost"] = np.log1p(summ["target_total_recovery_cost"])

summ.head()

c:\Users\brigh\Documents\amdari-internship\projects\terranova-predictive-analytics\venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

,disasterNumber,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountHmgp,target_pa_cost,target_total_recovery_cost,log_target_pa_cost,log_target_total_cost
0,3601,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
1,3602,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
2,4420,27279186.25,24356998.74,2922187.51,5.297529e+08,38905824.97,5.297529e+08,5.959379e+08,20.087921,20.205647
3,1971,77097372.06,57302364.20,19795007.86,2.010424e+08,63346282.14,2.010424e+08,3.414860e+08,19.119026,19.648817
4,4015,NaN,NaN,NaN,5.553128e+06,1762074.09,5.553128e+06,7.315202e+06,15.529872,15.805465

In [17]:
# engineer features from public assistance dataset to prepare for merging with disaster summaries and declarations dataset
pa = pub_assistance.copy()

pa_agg = (
    pa.groupby("disasterNumber")
    .agg(
        pa_project_count=("pwNumber", "count"),
        pa_total_obligated_sum=("totalObligated", "sum"),
        pa_total_obligated_mean=("totalObligated", "mean"),
        pa_total_obligated_median=("totalObligated", "median"),
        pa_total_obligated_max=("totalObligated", "max")
    )
    .reset_index()
)

print(pa_agg.shape[0])
pa_agg.head()

1067

,disasterNumber,pa_project_count,pa_total_obligated_sum,pa_total_obligated_mean,pa_total_obligated_median,pa_total_obligated_max
0,1871,249,18885702.86,75846.196225,6883.220,4447981.56
1,1872,1027,9308283.83,9063.567507,3628.310,881619.97
2,1873,494,13737974.24,27809.664453,8421.065,2013694.59
3,1874,422,22887905.74,54236.743460,6164.100,3466542.48
4,1875,372,24581140.89,66078.335726,5869.920,2666198.06

In [18]:
# check project size features
size_counts = (
    pa.pivot_table(
        index="disasterNumber",
        columns="projectSize",
        values="pwNumber",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

size_counts.columns = [str(c).lower() for c in size_counts.columns]

if "large" in size_counts.columns and "small" in size_counts.columns:
    size_counts["large_project_ratio"] = (
        size_counts["large"] / (size_counts["small"] + size_counts["large"])
    )
size_counts = size_counts.rename(columns={"disasternumber": "disasterNumber"})
size_counts.head()

   disasterNumber  large  small  large_project_ratio
0            1871     41    208             0.164659
1            1872     11   1016             0.010711
2            1873     59    435             0.119433
3            1874     80    342             0.189573
4            1875     71    301             0.190860

In [19]:
# check disasters with high ratio of large projects
print(size_counts[size_counts['large_project_ratio'] > 0.5].shape[0])
size_counts[size_counts['large_project_ratio'] > 0.5].head(10)

34

     disasterNumber  large  small  large_project_ratio
16             1887    249    244             0.505071
30             1901     28     27             0.509091
43             1914      8      4             0.666667
96             1968     51     24             0.680000
157            3486      4      2             0.666667
173            3530      3      2             0.600000
182            3553      2      1             0.666667
183            3557      1      0             1.000000
185            3560     17     11             0.607143
198            3600     11      8             0.578947

There have been 34 large scale disaster recovery projects since 2010.

In [20]:
# engineer feature to show state-level disaster frequency
state_freq = (
    decl.groupby("state")["disasterNumber"]
    .count()
    .rename("state_disaster_frequency")
    .reset_index()
)

decl = decl.merge(state_freq, on="state", how="left")

decl.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType,declaration_year,declaration_month,declaration_quarter,incident_duration_days,declaration_lag_days,incident_open_flag,state_disaster_frequency
0,5529,OR,Fire,2024-08-09 00:00:00+00:00,2024-08-08 00:00:00+00:00,NaT,FM,2024,8,3,NaN,1,1,294
1,5528,OR,Fire,2024-08-06 00:00:00+00:00,2024-08-04 00:00:00+00:00,NaT,FM,2024,8,3,NaN,2,1,294
2,5527,OR,Fire,2024-08-02 00:00:00+00:00,2024-08-02 00:00:00+00:00,NaT,FM,2024,8,3,NaN,0,1,294
3,4312,CA,Severe Storm,2017-05-02 00:00:00+00:00,2017-02-08 00:00:00+00:00,2017-02-11 00:00:00+00:00,DR,2017,5,2,3.0,83,0,739
4,4251,AL,Severe Storm,2016-01-21 00:00:00+00:00,2015-12-23 00:00:00+00:00,2015-12-31 00:00:00+00:00,DR,2016,1,1,8.0,29,0,743

### Merge

In [21]:
dis_fact = (
    decl
    .merge(summ, on="disasterNumber", how="left")
    .merge(pa_agg, on="disasterNumber", how="left")
    .merge(size_counts, on="disasterNumber", how="left")
)

dis_fact.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType,declaration_year,declaration_month,declaration_quarter,incident_duration_days,declaration_lag_days,incident_open_flag,state_disaster_frequency,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountHmgp,target_pa_cost,target_total_recovery_cost,log_target_pa_cost,log_target_total_cost,pa_project_count,pa_total_obligated_sum,pa_total_obligated_mean,pa_total_obligated_median,pa_total_obligated_max,large,small,large_project_ratio
0,5529,OR,Fire,2024-08-09 00:00:00+00:00,2024-08-08 00:00:00+00:00,NaT,FM,2024,8,3,NaN,1,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5528,OR,Fire,2024-08-06 00:00:00+00:00,2024-08-04 00:00:00+00:00,NaT,FM,2024,8,3,NaN,2,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5527,OR,Fire,2024-08-02 00:00:00+00:00,2024-08-02 00:00:00+00:00,NaT,FM,2024,8,3,NaN,0,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4312,CA,Severe Storm,2017-05-02 00:00:00+00:00,2017-02-08 00:00:00+00:00,2017-02-11 00:00:00+00:00,DR,2017,5,2,3.0,83,0,739,NaN,NaN,NaN,269934.77,1650.00,269934.77,271584.77,12.505939,12.512033,2.0,269934.77,134967.385000,134967.385,233307.18,1.0,1.0,0.500000
4,4251,AL,Severe Storm,2016-01-21 00:00:00+00:00,2015-12-23 00:00:00+00:00,2015-12-31 00:00:00+00:00,DR,2016,1,1,8.0,29,0,743,NaN,NaN,NaN,36201886.24,5530482.83,36201886.24,41732369.07,17.404622,17.546788,693.0,36201886.01,52239.373752,26674.610,1739135.15,51.0,642.0,0.073593

In [22]:
print(dis_fact.shape)
print(dis_fact.isnull().mean().sort_values(ascending=False))

(32473, 31)
totalAmountHaApproved         0.781418
totalAmountOnaApproved        0.653620
totalAmountIhpApproved        0.653435
totalObligatedAmountHmgp      0.370308
pa_total_obligated_max        0.349644
pa_total_obligated_mean       0.349644
pa_total_obligated_median     0.349644
pa_project_count              0.349644
pa_total_obligated_sum        0.349644
large                         0.349644
small                         0.349644
large_project_ratio           0.349644
totalObligatedAmountPa        0.326764
log_target_total_cost         0.015059
log_target_pa_cost            0.015059
target_pa_cost                0.013273
target_total_recovery_cost    0.013273
incidentEndDate               0.006775
incident_duration_days        0.006775
state_disaster_frequency      0.000000
incident_open_flag            0.000000
declaration_lag_days          0.000000
declaration_quarter           0.000000
disasterNumber                0.000000
state                         0.000000
declarationDate               0.000000
incidentType                  0.000000
declaration_year              0.000000
declaration_month             0.000000
incidentBeginDate             0.000000
declarationType               0.000000
dtype: float64

In [23]:
# checks for any discrepancies in total obligated amounts designated for public assistance between disaster summaries and public assistance datasets
dis_fact[['disasterNumber', 'totalObligatedAmountPa', 'pa_total_obligated_sum']].head(20)

    disasterNumber  totalObligatedAmountPa  pa_total_obligated_sum
0             5529                     NaN                     NaN
1             5528                     NaN                     NaN
2             5527                     NaN                     NaN
3             4312               269934.77               269934.77
4             4251             36201886.24             36201886.01
5             4251             36201886.24             36201886.01
6             4251             36201886.24             36201886.01
7             4251             36201886.24             36201886.01
8             4251             36201886.24             36201886.01
9             5516                     NaN                     NaN
10            5516                     NaN                     NaN
11            5514                     NaN                     NaN
12            5514                     NaN                     NaN
13            5514                     NaN                     NaN
14            5513                     NaN                     NaN
15            5512                     NaN                     NaN
16            5512                     NaN                     NaN
17            5511                     NaN                     NaN
18            5511                     NaN                     NaN
19            5511                     NaN                     NaN

In [24]:
# verify with ending rows
dis_fact[['disasterNumber', 'totalObligatedAmountPa', 'pa_total_obligated_sum']].tail(20)

       disasterNumber  totalObligatedAmountPa  pa_total_obligated_sum
32453            3643                     NaN                     NaN
32454            5626                     NaN                     NaN
32455            5628                     NaN                     NaN
32456            5627                     NaN                     NaN
32457            3598                21090.56                21090.56
32458            3598                21090.56                21090.56
32459            3598                21090.56                21090.56
32460            3598                21090.56                21090.56
32461            3598                21090.56                21090.56
32462            3598                21090.56                21090.56
32463            3598                21090.56                21090.56
32464            3598                21090.56                21090.56
32465            3598                21090.56                21090.56
32466            3598                21090.56                21090.56
32467            3598                21090.56                21090.56
32468            3598                21090.56                21090.56
32469            3598                21090.56                21090.56
32470            3598                21090.56                21090.56
32471            3598                21090.56                21090.56
32472            3598                21090.56                21090.56

In [25]:
dis_fact.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType,declaration_year,declaration_month,declaration_quarter,incident_duration_days,declaration_lag_days,incident_open_flag,state_disaster_frequency,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountHmgp,target_pa_cost,target_total_recovery_cost,log_target_pa_cost,log_target_total_cost,pa_project_count,pa_total_obligated_sum,pa_total_obligated_mean,pa_total_obligated_median,pa_total_obligated_max,large,small,large_project_ratio
0,5529,OR,Fire,2024-08-09 00:00:00+00:00,2024-08-08 00:00:00+00:00,NaT,FM,2024,8,3,NaN,1,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5528,OR,Fire,2024-08-06 00:00:00+00:00,2024-08-04 00:00:00+00:00,NaT,FM,2024,8,3,NaN,2,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5527,OR,Fire,2024-08-02 00:00:00+00:00,2024-08-02 00:00:00+00:00,NaT,FM,2024,8,3,NaN,0,1,294,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4312,CA,Severe Storm,2017-05-02 00:00:00+00:00,2017-02-08 00:00:00+00:00,2017-02-11 00:00:00+00:00,DR,2017,5,2,3.0,83,0,739,NaN,NaN,NaN,269934.77,1650.00,269934.77,271584.77,12.505939,12.512033,2.0,269934.77,134967.385000,134967.385,233307.18,1.0,1.0,0.500000
4,4251,AL,Severe Storm,2016-01-21 00:00:00+00:00,2015-12-23 00:00:00+00:00,2015-12-31 00:00:00+00:00,DR,2016,1,1,8.0,29,0,743,NaN,NaN,NaN,36201886.24,5530482.83,36201886.24,41732369.07,17.404622,17.546788,693.0,36201886.01,52239.373752,26674.610,1739135.15,51.0,642.0,0.073593

In [26]:
# create missing value indicators and fill missing values with zeros for funding feature columns - useful for model learning
summary_cols = [
    "totalAmountIhpApproved",
    "totalAmountHaApproved",
    "totalAmountOnaApproved",
    "totalObligatedAmountPa",
    "totalObligatedAmountHmgp"
]

pa_feature_cols = [
    "pa_project_count",
    "pa_total_obligated_sum",
    "pa_total_obligated_mean",
    "pa_total_obligated_median",
    "pa_total_obligated_max",
    "large",
    "small",
    "large_project_ratio"
]

for col in summary_cols:
    dis_fact[f"{col}_missing"] = dis_fact[col].isna().astype(int)

dis_fact[summary_cols] = dis_fact[summary_cols].fillna(0)
dis_fact[pa_feature_cols] = dis_fact[pa_feature_cols].fillna(0)

dis_fact.head()

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType,declaration_year,declaration_month,declaration_quarter,incident_duration_days,declaration_lag_days,incident_open_flag,state_disaster_frequency,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountHmgp,target_pa_cost,target_total_recovery_cost,log_target_pa_cost,log_target_total_cost,pa_project_count,pa_total_obligated_sum,pa_total_obligated_mean,pa_total_obligated_median,pa_total_obligated_max,large,small,large_project_ratio,totalAmountIhpApproved_missing,totalAmountHaApproved_missing,totalAmountOnaApproved_missing,totalObligatedAmountPa_missing,totalObligatedAmountHmgp_missing
0,5529,OR,Fire,2024-08-09 00:00:00+00:00,2024-08-08 00:00:00+00:00,NaT,FM,2024,8,3,NaN,1,1,294,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.000000,0.000000,0.0,0.00,0.000000,0.000,0.00,0.0,0.0,0.000000,1,1,1,1,0
1,5528,OR,Fire,2024-08-06 00:00:00+00:00,2024-08-04 00:00:00+00:00,NaT,FM,2024,8,3,NaN,2,1,294,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.000000,0.000000,0.0,0.00,0.000000,0.000,0.00,0.0,0.0,0.000000,1,1,1,1,0
2,5527,OR,Fire,2024-08-02 00:00:00+00:00,2024-08-02 00:00:00+00:00,NaT,FM,2024,8,3,NaN,0,1,294,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.000000,0.000000,0.0,0.00,0.000000,0.000,0.00,0.0,0.0,0.000000,1,1,1,1,0
3,4312,CA,Severe Storm,2017-05-02 00:00:00+00:00,2017-02-08 00:00:00+00:00,2017-02-11 00:00:00+00:00,DR,2017,5,2,3.0,83,0,739,0.0,0.0,0.0,269934.77,1650.00,269934.77,271584.77,12.505939,12.512033,2.0,269934.77,134967.385000,134967.385,233307.18,1.0,1.0,0.500000,1,1,1,0,0
4,4251,AL,Severe Storm,2016-01-21 00:00:00+00:00,2015-12-23 00:00:00+00:00,2015-12-31 00:00:00+00:00,DR,2016,1,1,8.0,29,0,743,0.0,0.0,0.0,36201886.24,5530482.83,36201886.24,41732369.07,17.404622,17.546788,693.0,36201886.01,52239.373752,26674.610,1739135.15,51.0,642.0,0.073593,1,1,1,0,0

In [27]:
print(dis_fact.isnull().mean().sort_values(ascending=False).head(20))

log_target_pa_cost            0.015059
log_target_total_cost         0.015059
target_total_recovery_cost    0.013273
target_pa_cost                0.013273
incident_duration_days        0.006775
incidentEndDate               0.006775
state                         0.000000
disasterNumber                0.000000
declarationDate               0.000000
incidentType                  0.000000
declaration_year              0.000000
declarationType               0.000000
declaration_lag_days          0.000000
incident_open_flag            0.000000
totalAmountIhpApproved        0.000000
state_disaster_frequency      0.000000
totalAmountHaApproved         0.000000
declaration_month             0.000000
declaration_quarter           0.000000
incidentBeginDate             0.000000
dtype: float64

In [28]:
# remove rows with missing target variable values
dis_fact = dis_fact[
    (dis_fact["target_total_recovery_cost"].notna()) &
    (dis_fact["target_pa_cost"].notna())
].copy()

print(dis_fact.shape[0])

32042

Removed only 431 records from 32473 records

In [29]:
print(dis_fact.isnull().mean().sort_values(ascending=False).head(20))

incident_duration_days      0.006242
incidentEndDate             0.006242
log_target_pa_cost          0.001810
log_target_total_cost       0.001810
declarationDate             0.000000
incidentType                0.000000
state                       0.000000
disasterNumber              0.000000
declaration_year            0.000000
declaration_month           0.000000
declarationType             0.000000
incidentBeginDate           0.000000
incident_open_flag          0.000000
state_disaster_frequency    0.000000
totalAmountIhpApproved      0.000000
totalAmountHaApproved       0.000000
totalAmountOnaApproved      0.000000
totalObligatedAmountPa      0.000000
declaration_quarter         0.000000
declaration_lag_days        0.000000
dtype: float64

In [30]:
# check distribution of incident types
print(dis_fact["incidentType"].value_counts())

incidentType
Severe Storm           7888
Biological             7856
Hurricane              6267
Flood                  3528
Severe Ice Storm       1377
Fire                   1374
Winter Storm           1331
Tropical Storm         1059
Snowstorm               604
Tornado                 300
Coastal Storm           184
Earthquake              137
Mud/Landslide            41
Typhoon                  28
Other                    22
Dam/Levee Break          10
Chemical                  9
Tsunami                   9
Tropical Depression       7
Terrorist                 4
Straight-Line Winds       3
Volcanic Eruption         2
Freezing                  1
Toxic Substances          1
Name: count, dtype: int64

In [31]:
# which incident types have highest total recovery costs?
dis_fact.groupby("incidentType")["target_total_recovery_cost"].median().sort_values(ascending=False)

incidentType
Volcanic Eruption      8.537624e+07
Biological             8.520353e+07
Mud/Landslide          3.709837e+07
Dam/Levee Break        3.598679e+07
Snowstorm              2.884641e+07
Flood                  2.629517e+07
Tornado                1.946545e+07
Severe Storm           1.623937e+07
Severe Ice Storm       1.269513e+07
Tsunami                7.901906e+06
Terrorist              6.195206e+06
Tropical Depression    4.508101e+06
Other                  3.828008e+06
Straight-Line Winds    2.217751e+06
Freezing               1.800764e+06
Chemical               1.639099e+06
Fire                   1.334899e+06
Hurricane              9.603639e+05
Coastal Storm          8.038185e+04
Earthquake             0.000000e+00
Tropical Storm         0.000000e+00
Toxic Substances       0.000000e+00
Typhoon                0.000000e+00
Winter Storm           0.000000e+00
Name: target_total_recovery_cost, dtype: float64

In [32]:
dis_fact.to_csv("../eda/disasters_fact_table.csv", index=False)